Fix language tags
deepsourcelabs/good-first-issue pull request #162
Opened 2020-10-16 08:22 UTC by ocean

Some progress on #127 

Not sure how to deal with all "unusual" characters in language names to make them URLs. At least, it's ok to use Hugo's `safeURL` function to get rid of unsafe characters, but because the language pages and the links to them are generated in two different places, they need to have the same logic applied to them to produce the same URLs.

2020-10-16 08:35 UTC, ocean commented
PR test is failing because the `'github.com/jina-ai/jina/'` is mentioned twice in `repositories.toml` 😢

2020-10-16 08:44 UTC, jai-deepsource commented
@ocean Remove the duplicate in this PR?

2020-10-20 03:37 UTC, ocean commented
Sorry, I left my test deployment files in, just removed them now. Ready for review, or at least further testing.

2020-10-20 04:50 UTC, ocean commented
Argh, still doesn't handle languages with spaces in them. Needs more work, but I hope I've moved things forward a little bit.

2020-10-21 16:58 UTC, rahul-deepsource requested changes
@ocean: Thanks for the PR! The changes look good. I've left a few comments. Also, it'd be great if you could add a few test cases to make sure that this works: Add some languages with weird characters in them (`C#`, etc.) and test that the regex substitution works fine.

2020-10-21 16:58 UTC, rahul-deepsource commented on gfi/populate.py
> +                        TAGS["Unknown"] += 1
I'm not sure if showing "Unknown" is a good idea. If there's no language for a repo, I think we should just leave it out.

```python3
if (language := repo_details["language"]:
    TAGS[language] += 1
```

2020-10-25 00:14 UTC, ocean commented on gfi/populate.py
> +                        TAGS["Unknown"] += 1
Ok, good idea about leaving out repos with unknown languages.

I will add some test cases too 👍

2020-12-22 07:22 UTC, sanket-deepsource commented
This has been handled in a recent release.

2020-12-22 07:22 UTC, closed without merging