LangTrans
deepsourcelabs/good-first-issue pull request #217
Opened 2021-02-27 05:55 UTC by B-R-P

LangTrans is a developer tool to customize syntax of programming language

2021-03-07 11:08 UTC, B-R-P commented
Issues Page: https://github.com/LangTrans/LangTrans/issues

2021-03-22 11:11 UTC, sanket-deepsource requested changes
Hi! Can you please add the repository in the correct lexicographic order?

2021-03-22 12:48 UTC, B-R-P commented
> Hi! Can you please add the repository in the correct lexicographic order?

Yes, I added the repository in lexicographic order.

2021-03-24 05:37 UTC, sanket-deepsource approved these changes

2021-03-24 05:37 UTC, merged