chore: add chaos-mesh to repositories.toml
deepsourcelabs/good-first-issue pull request #301
Opened 2021-07-30 06:52 UTC by STRRL

Signed-off-by: STRRL <str_ruiling@outlook.com>

#### ℹ️ Repository information

**The repository has**:

- [x] At least three issues with the good first issue label.
- [x] Detailed setup instructions for the project.
- [x] CONTRIBUTING.md
- [x] Actively maintained.

2021-07-30 09:54 UTC, shubhendra-deepsource commented on data/repositories.toml
>    'github.com/chatwoot/chatwoot',
```suggestion
  'github.com/CesiumGS/cesium',
  'github.com/chaos-mesh/chaos-mesh',
  'github.com/chapel-lang/chapel',
  'github.com/chatwoot/chatwoot',
```

2021-07-30 09:55 UTC, shubhendra-deepsource requested changes
@STRRL You missed it by one line. Make the change and we're good to go! 🚀

2021-08-01 06:21 UTC, STRRL commented
> @STRRL You missed it by one line. Make the change and we're good to go!

updated! PTAL! XD

2021-08-01 13:14 UTC, shubhendra-deepsource approved these changes
LGTM

2021-08-01 13:14 UTC, merged