add Project Harbor and Carvel and sort the list
deepsourcelabs/good-first-issue pull request #376
Opened 2022-01-17 09:34 UTC by OrlinVasilev

Signed-off-by: OrlinVasilev <ovasilev@vmware.com>

#### ℹ️ Repository information

**The repository has**:

- [X] At least three issues with the good first issue label.
- [X] Detailed setup instructions for the project.
- [X] CONTRIBUTING.md
- [X] Actively maintained.

2022-01-20 17:09 UTC, sanket-deepsource requested changes

2022-01-20 17:09 UTC, sanket-deepsource commented on data/repositories.toml
> +  'github.com/goharbor/harbor'
```suggestion
  'github.com/goharbor/harbor',
```

2022-01-20 17:09 UTC, sanket-deepsource commented on data/repositories.toml
> +  'github.com/vmware-tanzu/carvel'
```suggestion
  'github.com/vmware-tanzu/carvel',
```

2022-01-20 17:11 UTC, OrlinVasilev commented
@sanket-deepsource  thank you fixed!

2022-03-15 05:42 UTC, siddhant-deepsource reviewed
@OrlinVasilev Thanks for adding these amazing projects. Had one issue though with [vmware-tanzu/carvel](https://github.com/vmware-tanzu/carvel) that it doesn't contain any issue with the label `good-first-issue`. It would be great if you can at least open 3 beginner friendly issues on this project for new contributors. The other changes look good. 💯

2022-03-22 15:08 UTC, sanket-deepsource approved these changes

2022-03-22 15:08 UTC, sanket-deepsource requested changes
Hey @OrlinVasilev! Thanks for your contribution. Looks like there are some conflicts. Do you mind resolving them?

2022-03-22 15:26 UTC, sanket-deepsource approved these changes

2022-03-23 12:53 UTC, OrlinVasilev commented
Anyone to merge ? :)

2022-03-23 13:08 UTC, merged

2022-03-23 13:20 UTC, OrlinVasilev commented
Thank you!