Update repositories.toml
deepsourcelabs/good-first-issue pull request #379
Opened 2022-01-20 16:38 UTC by kgashok

added BlitzKraft/saythanks.io

#### ℹ️ Repository information

**The repository has**:

- [x] At least three issues with the good first issue label.
- [x] Detailed setup instructions for the project.
- [x] CONTRIBUTING.md
- [x] Actively maintained.

2022-01-20 17:05 UTC, sanket-deepsource commented on data/repositories.toml
> +  'github.com/BlitzKraft/saythanks.io'
```suggestion
  'github.com/BlitzKraft/saythanks.io',
```

2022-01-20 17:06 UTC, sanket-deepsource requested changes
Can you please add the repository in the correct lexicographic order?

2022-01-23 16:49 UTC, kgashok commented
> Can you please add the repository in the correct lexicographic order?

`A` comes before `a`, lexicographically. 
Since the repo is `BlitzKraft`, it appears at the top of the "b" list. 
Is that okay?

2022-01-23 16:49 UTC, kgashok commented on data/repositories.toml
> +  'github.com/BlitzKraft/saythanks.io'
Changed and submitted new PR.

2022-03-15 09:32 UTC, kgashok commented
> Thus, would be great if you can add the repo in correct alphabetical order. I guess it should be added after [github.com/bitcoin/bitcoin](https://github.com/kgashok/good-first-issue/blob/patch-3/data/repositories.toml?rgh-link-date=2022-03-15T09%3A07%3A34Z#L81). Thanks! 🙌

Done!

2022-03-15 11:39 UTC, sanket-deepsource approved these changes

2022-03-15 11:39 UTC, merged

2022-03-16 07:42 UTC, kgashok commented
Thanks much, @sanket-deepsource and @siddhant-deepsource !

2022-03-16 07:52 UTC, kgashok commented
@sanket-deepsource  
But the project saythanks.io does not show up https://goodfirstissue.dev/language/python site - how come?